### ISSUE TITLE
Validation based on models

### ISSUE THREAD

**Issue by rtimms** [FaradayInstitution/BPX#29]
Checking for required parameters should be done by model (e.g. SPM needs fewer parameters than DFN). Allows users to share "partial" BPX that is sufficient for reduced models.

**Comment by rtimms** [comment]
Have a warn or error on validation against a model. This would support sharing "partial" BPX files where all the fields are valid and consistent but not all the required parameters are there for any given model. Useful for e.g. sharing parameters fro a single electrode.

**Comment by ejfdickinson** [comment]
Do we have a standard specification document that says which parameters need to be defined for which models?

This is implied by [Ferran's paper](https://iopscience.iop.org/article/10.1088/2516-1083/ac7d31/meta) on which the original BPX (DFN) is based, but I think we need to express it formally before we can define the correctness or otherwise of the implementation in #34 .

@ikorotkin Did you make such a specification document? Otherwise I can put one together.
